baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Codox'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]
resourceDir = "../resources"

DefaultContentLanguage = "cn"
SectionPagesMenu = "main" 
pagination.pagerSize = 3                  # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "" 
enableRobotsTXT = true 

[languages]
[languages.en]
title = "Codox"
weight = 1
contentDir = "content/en"
# languageDirection = 'rtl' for Right-To-Left languages
[languages.cn]
title = "Codox"
weight = 2
contentDir = "content/cn"

[sitemap] 
  changefreq = "monthly" 
  priority = 0.5 
  filename = "sitemap.xml" 
 
[params] 
  text_color = "" 
  author = "" 
  favicon = "" 
  site_logo = "" 
  description = "The last theme you'll ever need. Maybe." 
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-" 
  background_color_class = "bg-black" 
  recent_posts_number = 3 
  commentoEnable = true 
 
[services.disqus] 
  shortname = 'coyace'
