baseURL = 'https://example.org/'
languageCode = 'zh-hans'
title = 'Codox'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]
resourceDir = "../resources"

pagination.pagerSize = 3                  # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "" 
enableRobotsTXT = true 
defaultContentLanguage = "zh-hans"
hasCJKLanguage = true

[languages]
[languages.zh-hans]
  title = "Codox"
  contentDir = "content/zh-hans"
  weight = 1

[sitemap] 
  changefreq = "monthly" 
  priority = 0.5 
  filename = "sitemap.xml" 

[markup.goldmark.renderer]
unsafe = true
 
[params] 
  text_color = "" 
  author = "" 
  favicon = "img/logo.svg" 
  site_logo = "img/logo.svg" 
  description = "The last theme you'll ever need. Maybe." 
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-" 
  background_color_class = "bg-black" 
  body_classes = "avenir bg-washed-yellow"
  recent_posts_number = 3 
  commentoEnable = true 
 
[services.disqus] 
  shortname = 'coyace'

[[menu.main]]
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
name = "文章列表"
url = "/post/"
weight = -2

[[menu.main]]
name="Contact"
url = "/contact"
weight = 3
